<?php
// This file is generated by compile.php. Do not edit directly.
$formats = array (
  0 => 
  array (
    'title' => 'P!P Championship Series',
    'cup' => 'championshipseries',
    'cp' => 1500,
    'meta' => 'championshipseries',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'hideRankings' => true,
  ),
  1 => 
  array (
    'title' => 'Master Premier Cup',
    'cup' => 'premier',
    'cp' => 10000,
    'meta' => 'premiermaster',
    'showCup' => true,
    'showFormat' => false,
    'showMeta' => true,
    'hideRankings' => true,
    'rules' => 
    array (
      0 => 'No CP limit.',
      1 => 'Legendary Pokémon, Mythical Pokémon, and Ultra Beasts are not eligible.',
    ),
  ),
  2 => 
  array (
    'title' => 'Little Cup',
    'cup' => 'little',
    'cp' => 500,
    'meta' => 'little',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  3 => 
  array (
    'title' => 'Catch Cup: Memories in Motion',
    'cup' => 'catch',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  4 => 
  array (
    'title' => 'Kanto Cup',
    'cup' => 'kanto',
    'cp' => 1500,
    'meta' => 'kanto',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  5 => 
  array (
    'title' => 'Spring Cup',
    'cup' => 'spring',
    'cp' => 1500,
    'meta' => 'spring',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  6 => 
  array (
    'title' => 'Jungle Cup',
    'cup' => 'jungle',
    'cp' => 1500,
    'meta' => 'jungle',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  7 => 
  array (
    'title' => 'Electric Cup',
    'cup' => 'electric',
    'cp' => 1500,
    'meta' => 'electric',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  8 => 
  array (
    'title' => 'Fantasy Cup',
    'cup' => 'fantasy',
    'cp' => 1500,
    'meta' => 'fantasy',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  9 => 
  array (
    'title' => 'Custom',
    'cup' => 'custom',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => false,
  ),
);
?>